spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webapp
    username: root
    password: 123456
  freemarker:
    suffix: .ftl
    # 配置后可以使用 ${request.contextPath}
    request-context-attribute: request
mybatis:
  # mapper 路径
  mapperLocations: classpath:mapper/*.xml
  # 扫描实体类
  typeAliasesPackage: com.tom.model
server:
  port: 80
# 日志输出级别
#logging:
#  level:
#    root: warn